title: Wangbingkun's Homepage
page-top-title: Wangbingkun
top-section-bg-text: Try my best
home-subtitle: Yourname&ensp;|&ensp;Wangbingkun
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
